# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KZwTzlwUcRaTVALGY-zxx6g5BTltco8a
"""

def Polynome(x) :
  ##############################################################################################
  ####      Cas 1: Chaine de caractère
  ##############################################################################################

  if (type(x)==str):
    print("Impossibilité de saisir un str dans la fonction")
    print("Veuillez saisir un valeur numérique:")
    x = int(input()) #### Saisie d'une nouvelle valeur pour x

  ##############################################################################################
  ####      Cas 2: Complexe
  ##############################################################################################
  elif (type(x) == complex):
     x = x.real

  ##############################################################################################
  ####      Cas 3: Nombre négatif
  ##############################################################################################
  elif (x < 0):
    x = abs(x)

  ##############################################################################################
  ####      Cas 4: Nombre trop grand
  ##############################################################################################

  elif (len(str(x)) > 5): #### Si la longeur de x > 5
    print("Impossibilité de saisir un nombre à 5 chiffres dans la fonction")
    print("Veuillez saisir un valeur numérique:")
    x = int(input()) #### Saisie d'une nouvelle valeur pour x

  ##############################################################################################
  ####      Cas 4: Nombre très petit
  ##############################################################################################

  elif (x < 1): #### Si x < 1
    print("Impossibilité de saisir un nombre plus petit que 1")
    print("Veuillez saisir un valeur numérique:")
    x = int(input()) #### Saisie d'une nouvelle valeur pour x
  
  return x**3-1.5*x**2-6*x+5

Polynome(0.5)