# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KZwTzlwUcRaTVALGY-zxx6g5BTltco8a
"""

def Factorielle(n):
  if n < 2:
    return 1
  else:
    return n*Factorielle(n-1)

Factorielle(5)