# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KZwTzlwUcRaTVALGY-zxx6g5BTltco8a
"""

def Fibonacci():
  f= input("entrer un nombre : ")
  f= int(f)
  if f == 0:
    print ("La suite fibonacci est : ")
    return [0]
  elif f == 1:
    print ("La suite fibonacci est : ")
    return [0,1]
  else:
    liste = [0,1]
    for i in range(2,f+1):
      liste+=[liste[-1]+liste[-2]]
    print ("La suite fibonacci est : ")
    return liste

Fibonacci()