# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KZwTzlwUcRaTVALGY-zxx6g5BTltco8a
"""

def Polynome(x) :
  return x**3-1.5*x**2-6*x+5

Polynome(5)